config/routes.rb
Rails.application.routes.draw do
  root   'sessions#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get    'signup' => 'users#new'
  get    'blog'   => 'posts#index'
  resources :users, except: [:index, :new, :destroy] do
    delete 'avatar', on: :member
  end
  resources :documents,       only: [:show, :create, :edit, :update, :destroy]
  resources :activations,     only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts,           only: [:new, :create, :show, :edit, :update] do
    resources :comments,      only: [:create]
  end
  resources :comments,         only: [:update, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :documents
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: {minimum: 5, maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :title, length: { maximum: 255 }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  has_attached_file :avatar, styles: { medium: '200x200#', thumb: '75x75#' },
    default_url: "#{Rails.application.secrets.public_asset_root}/img/avatars/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def User.digest(string)
    BCrypt::Password.create(string)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def update_activation_digest
    create_activation_digest
    save
  end

  private
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :avatar]
  before_action :correct_user,   only: [:show, :edit, :update, :avatar]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def avatar
    @user.avatar = nil
    @user.save
    flash[:success] = "Avatar deleted"
    redirect_to edit_user_path @user
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :title, :description, :password, :password_confirmation, :avatar)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.container
  .row
    .col-md-6.col-md-offset-3{style: 'padding-top: 55px; padding-bottom: 25px;'}
      = image_tag @user.avatar.url(:medium), class: 'medium-avatar'
      .delete-avatar
        = link_to avatar_user_path(@user), method: :delete, data: {confirm: 'Delete this image?'} do
          = icon('trash')
      = form_for @user, html: {role: 'form', multipart: true} do |f|
        .form-group
          = f.label :avatar
          = f.file_field :avatar
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :title
          = f.text_field :title, class: 'form-control'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, 'Confirmation'
          = f.password_field :password_confirmation, class: 'form-control'
        = f.submit 'Update', class: 'btn btn-large btn-primary'

app/views/users/new.html.haml
.vertical-center
  .container
    .row
      .col-md-4.col-md-offset-4
        %h1 Welcome!
        = form_for @user, html: {role: 'form'} do |f|
          = render 'shared/error_messages', object: f.object
          .form-group
            = f.text_field :name, placeholder: 'Name', class: 'form-control'
          .form-group
            = f.text_field :email, placeholder: 'Email', class: 'form-control'
          .form-group
            = f.password_field :password, placeholder: 'Password', class: 'form-control'
          .form-group
            = f.password_field :password_confirmation, placeholder: 'Re-enter Password', class: 'form-control'
          = f.submit 'Sign up', class: 'btn btn-large btn-primary'
          .below-form-link
            = link_to 'need a new activation email?', new_activation_path

app/views/users/show.html.haml
.user-left
  = image_tag @user.avatar.url(:medium), class: 'medium-avatar'
  %h2
    = @user.name
  %h3
    = @user.title
  .markdown
    = markdown @user.description.to_s
  %div
    .btn.btn-sm.btn-primary.toggle-edit{data: {id: 'descriptionform'}}
      = icon('edit')
      Edit info
  #descriptionform.toggle-form
    %a{href: 'https://guides.github.com/features/mastering-markdown/', target: '_blank'}
      You can use markdown here
      = icon('external-link')
    = form_for @user, html: {role: 'form'} do |f|
      .form-group
        = f.text_area :description, class: 'form-control', rows: 10
      = f.submit 'Update', class: 'btn btn-sm btn-primary pull-right'
      .btn.btn-sm.btn-default.pull-right.toggle-cancel{data: {id: 'descriptionform'}}
        Cancel
.user-container.container-fluid
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading
          = form_for current_user.documents.build, html: {class: 'pull-right', role: 'form'} do |f|
            = f.submit 'New Document', class: 'btn btn-primary'
          %h2
            Documents
        %table.table.table-hover
          - @user.documents.each do |d|
            %tr
              %td
                = link_to d.name, edit_document_path(d)
              %td.doc-time{data: {time: (d.updated_at.to_i * 1000)}}
              %td
                = link_to d, method: :delete, data: {confirm: "Are you sure? This can not be undone."} do
                  = icon('trash')