config/routes.rb
Rails.application.routes.draw do
  root   'sessions#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get    'signup' => 'users#new'
  get    'blog'   => 'posts#index'
  resources :users, except: [:index, :new, :destroy] do
    delete 'avatar', on: :member
  end
  resources :documents,       only: [:show, :create, :edit, :update, :destroy]
  resources :activations,     only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts,           only: [:new, :create, :show, :edit, :update] do
    resources :comments,      only: [:create]
  end
  resources :comments,         only: [:update, :destroy]

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user
  validates :name, presence: true, length: {minimum: 5, maximum: 50}
  validates :body, length: {minimum: 0, allow_nil: false, message: "can't be nil"}
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :create]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def show
    @document = Document.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @document.name.parameterize.underscore,
          layout: 'pdf.html',
          page_size: 'Letter',
          disposition: 'attachment',
          margin: {top: 0, bottom: 0, left: 0, right: 0},
          disable_javascript: false
      end
    end
  end

  def create
    document = current_user.documents.create(name: "Document #{current_user.documents.count + 1}", body: "")
    redirect_to edit_document_path document
  end

  def edit
  end

  def update
    respond_to do |format|
      if @document.update_attributes(document_params)
        format.html do
          flash[:success] = 'Document name updated'
          redirect_to edit_document_path(@document)
        end
        format.json { head :no_content }
      else
        format.html do
          flash[:danger] = @document.errors.to_a.join(". ")
          redirect_to edit_document_path(@document)
        end
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document.destroy
    flash[:success] = "Document deleted"
    redirect_to current_user
  end

  private
    def document_params
      params.require(:document).permit(:name, :body)
    end

    def correct_user
      @document = Document.find(params[:id])
      redirect_to(root_url) unless current_user?(@document.user)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.haml
#document-editor{tabindex: '0'}
  = render 'editor_toolbar', url: url_for(document) if editable
  #document-editor-pages= document.body.html_safe

app/views/documents/_document_info.html.haml
.container
  .row
    .col-xs-4.doc-info{style: 'border-right: 1px solid #ccc;'}
      = link_to @document.user, class: 'pull-left', style: 'margin-right: 10px;' do
        = image_tag @document.user.avatar.url(:thumb), class: 'thumb-avatar'
      %h3= @document.user.name
      %em.small= @document.user.title
    .col-xs-6.doc-info
      %h1
        - if edit_modal
          %a{href: '#', data: {toggle: 'modal', target: '#name-edit-modal'}}= @document.name
        - else
          = @document.name
      %em.small Warning--the editor is still in beta
      %br
      %em#doc-saved-at.small
    .col-xs-2.doc-info
      = link_to document_path(@document, format: :pdf), class: 'btn btn-primary bottom-tooltip', title: 'Print to pdf' do
        = icon('print')
      %button.btn.btn-primary{type: 'button', data: {toggle: 'modal', target: '#share-modal'}}
        Share

= content_for :modals do
  - if edit_modal
    #name-edit-modal.modal.fade{tabindex: '-1', role: 'dialog',
      aria: {labelledby: 'name-edit-label', hidden: 'true'}}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{type: 'button', data: {dismiss: 'modal'}, aria: {label: 'Close'}}
              %span{aria: {hidden: 'true'}} &times;
            %h4#name-edit-label.modal-title Rename document
          .modal-body
            = form_for @document, html: {role: 'form'} do |f|
              .form-group
                = f.label :name, 'New name'
                = f.text_field :name, class: 'form-control'
              = f.submit 'Update', class: 'btn btn-primary'
              %button.btn.btn-default{type: 'button', data: {dismiss: 'modal'}} Close

  #share-modal.modal.fade{tabindex: '-1', role: 'dialog',
    aria: {labelledby: 'share-label', hidden: 'true'}}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{type: 'button', data: {dismiss: 'modal'}, aria: {label: 'Close'}}
            %span{aria: {hidden: 'true'}} &times;
          %h4#share-label.modal-title Share document
        .modal-body
          = link_to document_url(@document), target: '_blank' do
            View published version
            = icon('external-link')
          %h5 Or copy this shareable link
          .input-group
            %input#share-link.form-control{value: document_url(@document), readonly: true}
            %span#share-clip-wrap.input-group-btn{data: {toggle: 'tooltip', placement: 'top'},
              title: 'Copy to clipboard'}
              %button#share-clip.btn.btn-default{type: 'button',
                data: {clipboard: {text: 'error copying link', target: 'share-link'}}}
                = icon('link')

app/views/documents/_editor_toolbar.html.haml
#document-editor-toolbar.scroll-watch{data: {url: url}}
  .toolbar-wrapper
    .editor-group
      %button#print-button.editor-button
        = icon('print')
    .editor-group.dropdown#font-fam-select
      %button.editor-select-button.drop-button{data: {dropid: '#font-fam-select'}}
        %span Arial
        = icon('caret-down')
      %ul.dropdown-list
        - ['Arial', 'Comic Sans MS', 'Courier New', 'Georgia',
          'Impact', 'Times New Roman', 'Trebuchet MS', 'Verdana'].each do |font_fam|
          %li{style: "font-family: '#{font_fam}';"}= font_fam
    .editor-group.dropdown#font-size-select
      %button.editor-select-button.drop-button{data: {dropid: '#font-size-select'}}
        %span 8
        = icon('caret-down')
      %ul.dropdown-list
        - [8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72, 96].each do |font_size|
          %li= font_size
    .editor-group
      %input#bold-checkbox.editor-checkbox{type: 'checkbox'}
      %label{for: 'bold-checkbox'}
        = icon('bold', '', class: 'strong')
      %input#italic-checkbox.editor-checkbox{type: 'checkbox'}
      %label{for: 'italic-checkbox'}
        = icon('italic')
      %input#underline-checkbox.editor-checkbox{type: 'checkbox'}
      %label{for: 'underline-checkbox'}
        = icon('underline')
    .editor-group
      %input#left-checkbox.editor-checkbox{type: 'radio', name: 'align', value: 'left'}
      %label{for: 'left-checkbox'}
        = icon('align-left')
      %input#center-checkbox.editor-checkbox{type: 'radio', name: 'align', value: 'center'}
      %label{for: 'center-checkbox'}
        = icon('align-center')
      %input#right-checkbox.editor-checkbox{type: 'radio', name: 'align', value: 'right'}
      %label{for: 'right-checkbox'}
        = icon('align-right')
      %input#justify-checkbox.editor-checkbox{type: 'radio', name: 'align', value: 'justify'}
      %label{for: 'justify-checkbox'}
        = icon('align-justify')
    .editor-group.dropdown#line-height-select
      %button.editor-select-button.drop-button{data: {dropid: '#line-height-select'}}
        %span Single
        = icon('caret-down')
      %ul.dropdown-list
        - [['Single', '1'], ['1.15', '1.15'], ['1.5', '1.5'], ['Double', '2']].each do |spacing, value|
          %li{data: {value: value}}= spacing
    .editor-group
      %input#ol-checkbox.editor-checkbox{type: 'checkbox'}
      %label{for: 'ol-checkbox'}
        = icon('list-ol')
      %input#ul-checkbox.editor-checkbox{type: 'checkbox'}
      %label{for: 'ul-checkbox'}
        = icon('list-ul')
      %button#outdent-button.editor-button
        = icon('outdent')
      %button#indent-button.editor-button
        = icon('indent')

app/views/documents/edit.html.haml
#document-info
  #document-info-wrapper
    = link_to root_path, id: 'home-bars' do
      = icon('bars', '', class: 'fa-inverse')
    = render 'document_info', edit_modal: true

= render @document, editable: true

app/views/documents/show.html.haml
#document-info.scroll-watch
  #document-info-wrapper
    - if logged_in?
      = link_to root_path, id: 'home-bars' do
        = icon('bars', '', class: 'fa-inverse')
    = render 'document_info', edit_modal: false

= render @document, editable: false

app/views/documents/show.pdf.haml
= @document.body.html_safe