config/routes.rb
Rails.application.routes.draw do
  root   'sessions#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get    'signup' => 'users#new'
  get    'blog'   => 'posts#index'
  resources :users, except: [:index, :new, :destroy] do
    delete 'avatar', on: :member
  end
  resources :documents,       only: [:show, :create, :edit, :update, :destroy]
  resources :activations,     only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts,           only: [:new, :create, :show, :edit, :update] do
    resources :comments,      only: [:create]
  end
  resources :comments,         only: [:update, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update]
  before_action :admin_user #,     only: [:new, :create, :edit, :update]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user: current_user))
    if @post.save
      flash[:success] = "Post created"
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to @post
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:name, :content)
    end

    def admin_user
      unless current_user.email == "bryant.daniel.j@gmail.com"
        flash[:danger] = "Admin privileges are required."
        redirect_to(root_url)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.posts-container.container
  .row
    .col-md-8.col-md-offset-2
      = render 'header'
      = form_for @post, html: {role: 'form'} do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          = f.text_field :name, placeholder: 'Name', class: 'form-control'
        .form-group
          = f.text_area :content, placeholder: 'Content', class: 'form-control', rows: 50
        = f.submit 'Publish', class: 'btn btn-large btn-primary'

app/views/posts/_header.html.haml
.posts-header
  You are reading a
  = link_to 'blog', blog_path
  about nothing,
  - if logged_in?
    signed in as
    = link_to "#{current_user.name}.", current_user
  - else
    not
    = link_to 'signed in.', login_path

app/views/posts/_post.html.haml
.post
  %h1.post-name
    = link_to post.name, post
  .post-info
    = link_to post.user.name, post.user
    wrote this on
    = post.created_at.strftime('%b %d')
  .post-content
    = markdown post.content

app/views/posts/edit.html.haml
= render 'form'

app/views/posts/index.html.haml
.posts-container.container
  .row
    .col-md-8.col-md-offset-2
      = render 'header'
      = render @posts

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
.posts-container.container
  .row
    .col-md-8.col-md-offset-2
      = render 'header'
      = render @post
      = render @post.comments
      .comment.clearfix
        - if logged_in?
          = form_for Comment.new, url: post_comments_path(@post), html: {role: 'form'} do |f|
            = render 'shared/error_messages', object: f.object
            .form-group
              = f.text_area :content, placeholder: 'Share your thoughts...',
                class: 'form-control', rows: 10, required: true
            = f.submit 'Add comment', class: 'btn btn-large btn-primary pull-right'
        - else
          = link_to "Login", login_path
          or
          = link_to "sign up", signup_path
          to comment.