config/routes.rb
Rails.application.routes.draw do
  root   'sessions#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get    'signup' => 'users#new'
  get    'blog'   => 'posts#index'
  resources :users, except: [:index, :new, :destroy] do
    delete 'avatar', on: :member
  end
  resources :documents,       only: [:show, :create, :edit, :update, :destroy]
  resources :activations,     only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts,           only: [:new, :create, :show, :edit, :update] do
    resources :comments,      only: [:create]
  end
  resources :comments,         only: [:update, :destroy]

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Resume Builder
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash.any?
      #flash-box
        - flash.each do |message_type, message|
          %div
            = message
    - if logged_in? && controller_name != 'documents'
      %nav.navbar.navbar-fixed-top
        .container-fluid{style: 'padding-right: 50px;'}
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to current_user.name, current_user, class: 'sm-nav-link'
            %li.bottom-tooltip{title: 'Account'}
              = link_to edit_user_path(current_user), class: 'sm-nav-link' do
                = icon('cog', '', class: 'fa-lg')
            %li.bottom-tooltip{title: 'Sign out'}
              = link_to logout_path, method: :delete, class: 'sm-nav-link' do
                = icon('sign-out', '', class: 'fa-lg')
    = yield
    <!-- Modals -->
    = content_for :modals

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Resume Builder
    = csrf_meta_tags
    :css
      // replicate some bootstrap styles
      body {
        margin: 0;
      }
      * {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
      }

  %body
    = yield